filename: congress_infobeamer.svg # output file name
width: 1414 # used for aspect ratio
height: 1000 # used for aspect ratio
grid: !!python/tuple [28, 14] # background grid size, 20x20 = full dinA* with scale 0.05
grid_padding: !!python/tuple [0, 0]
scale: 0.05 # scale of single segment

blur:
  blur: true
  strength: 40 # apply some blur, let the segments shine :3 

png:
  print: true
  width: 8248 # 420 dpi
  height: 5833

color:
  background:  !!python/tuple [0.165, 0.165, 0.165] # background color, placed behind all segments
  segment_on:  !!python/tuple [0.0, 0.996, 0.71] # segment on color
  segment_off: !!python/tuple [0.16, 0.3, 0.29] # segment off color
  segment_bg:  !!python/tuple [0.1, 0.2, 0.19] # segment background (rectangle) color

root:
  start: [] # starting point position, number of elements must match seed. Leave emtpy for no roots
  seed: ["chaos ", "communication", "congress"] # n start points = n seeds. Leave empty ("") for random seed
  depth: 14 # max root depth before it dies

text: # list of strings/chars to be placed
  - 0:
    scaler: 1 # a scaler of 1 means a single char will be placed on the defined grid with scale
    x: 0
    y: 0
    buf:
      - [ 4, 8," "]
      - [ 5, 8," "]
      - [ 6, 8," "]
      - [ 7, 8," "]
      - [ 8, 8," "]
      - [ 9, 8," "]
      - [10, 8," "]
      - [11, 8," "]
      - [12, 8," "]
      - [13, 8," "]
      - [14, 8," "]
      - [15, 8," "]
      - [16, 8," "]
      - [17, 8," "]
      - [18, 8," "]
      - [19, 8," "]
      - [18, 9," "]
      - [20, 9," "]
      - [21, 9," "]
      - [22, 9," "]
      - [23, 9," "]
      - [24, 9," "]
      - [ 5, 9," "]
      - [ 5, 9," "]
      - [ 5, 9," "]
      - [ 5, 9," "]
  - 1:
    scaler: 1 # a scaler of 1 means a single char will be placed on the defined grid with scale
    x: 0
    y: 0
    buf:
      - [ 5, 9,  "C"]
      - [ 6, 9,  "O"]
      - [ 7, 9,  "M"]
      - [ 8, 9,  "M"]
      - [ 9, 9,  "O"]
      - [10, 9,  "N"]
      - [12, 9,  "C"]
      - [13, 9,  "O"]
      - [14, 9,  "D"]
      - [15, 9,  "E"]
      - [16, 9,  "("]
      - [17, 9,  ")"]
      - [ 8, 10, "D"]
      - [ 9, 10, "I"]
      - [10, 10, "F"]
      - [11, 10, "F"]
      - [12, 10, "E"]
      - [13, 10, "R"]
      - [14, 10, "E"]
      - [15, 10, "N"]
      - [16, 10, "T"]
      - [18, 10, "R"]
      - [19, 10, "O"]
      - [20, 10, "O"]
      - [21, 10, "T"]
      - [22, 10, "S"]
  - 2:
    scaler: 4 # a scaler of 3 means that the chars are three times the size, they are still placed on the grid
              # use x,y to move them by fractions of scalar
    x: 2
    y: 0
    buf:
      - [0, 4, "G"]
      - [1, 4, "P"]
      - [2, 4, "N"]
      - [3, 4, "-"]
      - [4, 4, "2"]
      - [5, 4, "2"]
