filename: gpn22_blue.svg
width: 1000
height: 1414
grid: !!python/tuple [20, 18]
grid_padding: !!python/tuple [0, 2]
scale: 0.05

blur:
  blur: true
  strength: 40 # apply some blur, let the segments shine :3 

png:
  print: true
  width: 5833 # 420 dpi
  height: 8248

color:
  background:  !!python/tuple [0.165, 0.165, 0.165]
  segment_on:  !!python/tuple [0.651, 0.914, 0.961]
  segment_off: !!python/tuple [0.192, 0.271, 0.268]
  segment_bg:  !!python/tuple [0.063, 0.090, 0.094]

root:
  seed: ["mau", "meow", "nya"]
  start: [6, 11, 16]
  depth: 7

text: # list of texts to be printed
  - 1:
    size: 0.035
    font: "Oxanium"
    x: 0.5
    y: 0.935
    alignment: "Center"
    color:  !!python/tuple [1, 1, 1]
    string: "30.05 - 02.06.2024  |  ZKM/HFG Karlsruhe"
  - 2:
    size: 0.035
    font: "Oxanium"
    x: 0.5
    y: 0.975
    alignment: "Center"
    color:  !!python/tuple [1, 1, 1]
    string: "Entropia e.V. / CCC Karlsruhe  |  gulas.ch"

segment:
  - 1:
    scaler: 1
    x: 0
    y: 0
    buf:
      - [ 2,14,"C"]
      - [ 3,14,"O"]
      - [ 4,14,"M"]
      - [ 5,14,"M"]
      - [ 6,14,"O"]
      - [ 7,14,"N"]
      - [ 9,14,"C"]
      - [10,14,"O"]
      - [11,14,"D"]
      - [12,14,"E"]
      - [13,14,"("]
      - [14,14,")"]
      - [ 3,15,"D"]
      - [ 4,15,"I"]
      - [ 5,15,"F"]
      - [ 6,15,"F"]
      - [ 7,15,"E"]
      - [ 8,15,"R"]
      - [ 9,15,"E"]
      - [10,15,"N"]
      - [11,15,"T"]
      - [13,15,"R"]
      - [14,15,"O"]
      - [15,15,"O"]
      - [16,15,"T"]
      - [17,15,"S"]
  - 2:
    scaler: 3
    x: 1
    y: 0
    buf:
      - [ 0,10,"G"]
      - [ 1,10,"P"]
      - [ 2,10,"N"]
      - [ 3,10,"-"]
      - [ 4,10,"2"]
      - [ 5,10,"2"]
