filename: gpn22_red.svg
width: 1000
height: 1414
grid: !!python/tuple [20, 18]
scale: 0.05

color:
  background:  !!python/tuple [0.165, 0.165, 0.165]
  segment_on:  !!python/tuple [0.988, 0.941, 0.365] # glow color #7F160B
  segment_off: !!python/tuple [0.498, 0.086, 0.043]
  segment_bg:  !!python/tuple [0.2, 0.153, 0.149]

root:
  seed: ["g", "p", "N"]
  start: [2, 8, 15]
  depth: 7

text:
  - 1:
    scaler: 1
    x: 0
    y: 0
    buf:
      - [ 2,14,"C"]
      - [ 3,14,"O"]
      - [ 4,14,"M"]
      - [ 5,14,"M"]
      - [ 6,14,"O"]
      - [ 7,14,"N"]
      - [ 9,14,"C"]
      - [10,14,"O"]
      - [11,14,"D"]
      - [12,14,"E"]
      - [13,14,"("]
      - [14,14,")"]
      - [ 3,15,"D"]
      - [ 4,15,"I"]
      - [ 5,15,"F"]
      - [ 6,15,"F"]
      - [ 7,15,"E"]
      - [ 8,15,"R"]
      - [ 9,15,"E"]
      - [10,15,"N"]
      - [11,15,"T"]
      - [13,15,"R"]
      - [14,15,"O"]
      - [15,15,"O"]
      - [16,15,"T"]
      - [17,15,"S"]
  - 2:
    scaler: 3
    x: 1
    y: 0
    buf:
      - [ 0,10,"G"]
      - [ 1,10,"P"]
      - [ 2,10,"N"]
      - [ 3,10,"-"]
      - [ 4,10,"2"]
      - [ 5,10,"2"]