filename: sign_landscape_empty.svg # output file name
width: 1414 # used for aspect ratio
height: 1000 # used for aspect ratio
grid: !!python/tuple [28, 14] # background grid size, 20x20 = full dinA* with scale 0.05
#grid_padding: !!python/tuple [28, 14]
scale: 0.0505 # scale of single segment

blur:
  blur: true
  strength: 40 # apply some blur, let the segments shine :3 

png:
  print: true
  width: 1920 # 420 dpi
  height: 1358

colors:
  background:  !!python/tuple [1, 1, 1] # background color, placed behind all segments
  segment_on:  !!python/tuple [0.0, 0.996, 0.71] # segment on color
  segment_off: !!python/tuple [0.16, 0.3, 0.29] # segment off color
  segment_bg:  !!python/tuple [0.1, 0.2, 0.19] # segment background (rectangle) color

roots:
  start: [] # starting point position, number of elements must match seed. Leave emtpy for no roots
  seed: [] # n start points = n seeds. Leave empty ("") for random seed
  depth: 0 # max root depth before it dies
  blur: 40 # glow strength, 0 to turn off

texts: # list of texts to be printed
  - 1:
    size: 0.18
    font: "Oxanium"
    x: 0.5
    y: 0.35
    alignment: "Center"
    color:  !!python/tuple [0, 0, 0]
    string: "Infodesk"
    blur: 10 # glow strength, 0 to turn off
  - 2:
    size: 0.05
    font: "Oxanium"
    x: 0.5
    y: 0.55
    alignment: "Center"
    color:  !!python/tuple [0.165, 0.165, 0.165]
    string: "very important message here"
    blur: 10 # glow strength, 0 to turn off

#panel: # grid of turned off segments
#  x: 0
#  y: 0
#  w: 0
#  h: 0

segments: # list of strings/chars to be placed
  - 0:
    scaler: 1 # a scaler of 1 means a single char will be placed on the defined grid with scale
    x: 0
    y: 0
    blur: 40 # glow strength, 0 to turn off
    buf:  # todo generative
      - [  0, 13,  " "] # left segments
      - [  1, 13,  " "]
      - [  2, 13,  " "]
      - [  3, 13,  " "]
      - [  4, 13,  " "]
      - [  5, 13,  " "]
      - [  6, 13,  " "]
      - [  7, 13,  " "]
      - [  0, 12,  " "]
      - [  1, 12,  " "]
      - [  2, 12,  " "]
      - [  3, 12,  " "]
      - [  4, 12,  " "]
      - [  0, 11,  " "]
      - [  1, 11,  " "]
      - [  0, 10,  " "]
      - [  0,  9,  " "]
      - [ 15, 13,  " "] # right segments
      - [ 21, 11,  " "]
      - [ 22, 11,  " "]
      - [ 23, 11,  " "]
      - [ 24, 11,  " "]
      - [ 25, 11,  " "]
      - [ 26, 11,  " "]
      - [ 27, 11,  " "]
      - [ 25, 10,  " "]
      - [ 26, 10,  " "]
      - [ 27, 10,  " "]
      - [ 27,  9,  " "]
  - 2:
    scaler: 2 # a scaler of 3 means that the chars are three times the size, they are still placed on the grid
              # use x,y to move them by fractions of scalar
    x: 0
    y: 0
    blur: 40 # glow strength, 0 to turn off
    buf:
      - [ 8, 12, "G"]
      - [ 9, 12, "P"]
      - [10, 12, "N"]
      - [11, 12, "-"]
      - [12, 12, "2"]
      - [13, 12, "2"]