filename: sticker_root_green.svg # output file name
width: 1000 # used for aspect ratio
height: 1414 # used for aspect ratio
grid: !!python/tuple [20, 20] # background grid size, 20x20 = full dinA* with scale 0.05
scale: 0.0505

blur:
  blur: true
  strength: 40 # apply some blur, let the segments shine :3 

png:
  print: true
  width: 2480 # 300 dpi dinA1
  height: 3508
  #width: 2480 # 300 dpi dinA4
  #height: 3508

colors:
  background:  !!python/tuple [0.165, 0.165, 0.165] # background color, placed behind all segments
  segment_on:  !!python/tuple [0.000, 0.996, 0.710] # segment on color
  segment_off: !!python/tuple [0.160, 0.300, 0.290] # segment off color
  segment_bg:  !!python/tuple [0.100, 0.200, 0.190] # segment background (rectangle) color

roots:
  seed: ["nyaa"] # n seeds = n start points. Leave empty ("") for random seed - "alerta~~~"
  start: [10] # starting point position, number of elements must match seed
  depth: 9 # max root depth before it dies

#texts: # list of texts to be printed

panel: # grid of turned off segments
  x: 0
  y: 0
  w: 20
  h: 18

#segments: # list of 14 segment chars to be placed with grid coordinates
